### ISSUE TITLE
[ADD]: Github Actions 를 추가 - Build 체크, SwiftLint 체크

### ISSUE THREAD

**Issue by cozytk** [DeveloperAcademy-POSTECH/MacC-Team-FourFour#6]
### Feature 설명

https://github.com/DeveloperAcademy-POSTECH/MC3-Team6-HaKenLuRooCo/tree/develop/.github/workflows

기존 챌린지에서 사용했던 Github Action 파일입니다.

```yml
# workflow 의 이름
name: Run Test

on: [pull_request]

jobs:
#  build 체크
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Build Test
      run: xcodebuild build -workspace TodayAnbu.xcworkspace -scheme TodayAnbu -destination 'platform=iOS Simulator,OS=15.5,name=iPhone 13 Pro'

  SwiftLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: GitHub Action for SwiftLint (Only files changed in the PR) with --strict
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict
```

위와 같은 식으로 1) 빌드에 성공하는지 확인하고 2) Lint가 적용되어 있는지 확인합니다.

<img width="950" alt="스크린샷 2022-10-09 오후 8 44 52" src="https://user-images.githubusercontent.com/59143479/194755093-d1e53084-de88-4b02-8ba2-80f74ba86dc1.png">

실패시 위 사진 처럼 PR 오른쪽 하단에 X 표시가 생기고

https://github.com/DeveloperAcademy-POSTECH/MC3-Team6-HaKenLuRooCo/actions/runs/2836962056

눌러보면 위 링크와 같은 페이지로 넘어가게 됩니다.

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/59143479/194755159-63787169-2371-4389-965c-4f614f46d7bd.png">

SwiftLint 같은 경우 PR 내부에서 어떤 걸 안지켰는지 확인할 수 있습니다!!

cc. @KimDaeSeong8721 @JIW00NG @dani

### 우선순위

★

### 예상 작업 기간

~ 10/12(화)
